# Generated by Django 6.1 on 2026-08-28 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Takım / Grup Adı"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Açıklama / Yaş Grubu"
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Varsayılan Aylık Aidat (TL)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coaches",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["coach", "club_admin"]},
                        related_name="assigned_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sorumlu Antrenörler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Takım",
                "verbose_name_plural": "Takımlar",
            },
        ),
    ]
