# Generated by Django 6.1 on 2026-09-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_move_monthly_fees_to_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTrainingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pazartesi"),
                            (1, "Salı"),
                            (2, "Çarşamba"),
                            (3, "Perşembe"),
                            (4, "Cuma"),
                            (5, "Cumartesi"),
                            (6, "Pazar"),
                        ],
                        verbose_name="Gün",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Başlangıç saati")),
                ("end_time", models.TimeField(verbose_name="Bitiş saati")),
                ("location", models.CharField(max_length=255, verbose_name="Yer")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_schedules",
                        to="teams.team",
                        verbose_name="Takım",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haftalık Antrenman Programı",
                "verbose_name_plural": "Haftalık Antrenman Programları",
                "ordering": ("weekday", "start_time"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "weekday"), name="unique_team_training_day"
                    )
                ],
            },
        ),
    ]
