# Generated by Django 6.1 on 2026-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_teamtrainingschedule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teamtrainingschedule",
            name="unique_team_training_day",
        ),
        migrations.AddField(
            model_name="teamtrainingschedule",
            name="training_type",
            field=models.CharField(
                choices=[("land", "Kara"), ("swimming", "Yüzme")],
                default="swimming",
                max_length=10,
                verbose_name="Antrenman türü",
            ),
        ),
    ]
