# Generated by Django 6.1 on 2026-09-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0010_athlete_last_sms_time"),
        ("teams", "0004_remove_teamtrainingschedule_unique_team_training_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTrainingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_date", models.DateField(verbose_name="Antrenman tarihi")),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="Katıldı mı?"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Not")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_attendance_records",
                        to="athletes.athlete",
                        verbose_name="Sporcu",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="teams.teamtrainingschedule",
                        verbose_name="Haftalık antrenman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrenman katılım kaydı",
                "verbose_name_plural": "Antrenman katılım kayıtları",
                "ordering": (
                    "-training_date",
                    "athlete__first_name",
                    "athlete__last_name",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule", "athlete", "training_date"),
                        name="unique_training_attendance_record",
                    )
                ],
            },
        ),
    ]
