# Generated by Django 6.1 on 2026-09-16 08:32

from django.db import migrations, models


def copy_attendance_status(apps, schema_editor):
    Attendance = apps.get_model("teams", "TeamTrainingAttendance")
    Attendance.objects.filter(attended=True).update(status="attended")


def restore_attended_flag(apps, schema_editor):
    Attendance = apps.get_model("teams", "TeamTrainingAttendance")
    Attendance.objects.filter(status="attended").update(attended=True)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_teamtrainingattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtrainingattendance",
            name="status",
            field=models.CharField(
                choices=[("attended", "Katıldı"), ("absent", "Katılmadı")],
                default="absent",
                max_length=10,
                verbose_name="Katılım durumu",
            ),
        ),
        migrations.RunPython(copy_attendance_status, restore_attended_flag),
        migrations.RemoveField(
            model_name="teamtrainingattendance",
            name="attended",
        ),
    ]
