# Generated by Django 6.1 on 2026-08-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0003_athlete_custom_fee_athlete_team"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentrecord",
            options={
                "ordering": ["-period", "created_at"],
                "verbose_name": "Gelir / Ödeme Kaydı",
                "verbose_name_plural": "Gelir / Ödeme Kayıtları",
            },
        ),
        migrations.AlterUniqueTogether(
            name="paymentrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank", "Banka Transferi / EFT / Havale"),
                    ("cash", "Elden / Nakit"),
                    ("credit_card", "Kredi Kartı"),
                    ("other", "Diğer"),
                ],
                default="bank",
                max_length=20,
                verbose_name="Ödeme Yöntemi",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("fee", "Aidat"),
                    ("donation", "Bağış"),
                    ("membership", "Üyelik"),
                    ("bank_transfer", "Banka / Havale Geliri"),
                    ("sponsorship", "Sponsorluk"),
                    ("event_license", "Lisans / Etkinlik Ücreti"),
                    ("other", "Diğer"),
                ],
                default="fee",
                max_length=30,
                verbose_name="Ödeme Türü",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Tutar (TL)"
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="athletes.athlete",
                verbose_name="Sporcu",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Not / Dekont No / Açıklama"
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="period",
            field=models.CharField(
                db_index=True,
                help_text="Format: YYYY-MM (Örn: 2026-08)",
                max_length=7,
                verbose_name="Gelir Dönemi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentrecord",
            unique_together={("athlete", "period", "payment_type")},
        ),
    ]
