# Generated by Django 6.1 on 2026-08-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0003_athlete_custom_fee_athlete_team"),
        ("finance", "0002_alter_paymentrecord_options_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteFeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_histories",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TeamFeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "start_date",
                    models.DateField(
                        help_text="Fiyatın geçerli olmaya başladığı tarih"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Boş ise halen geçerlidir", null=True
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_histories",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
