# Generated by Django 6.1.1 on 2026-09-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_athletefeehistory_teamfeehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Gider Kaydı', 'verbose_name_plural': 'Gider Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Gider Kategorisi', 'verbose_name_plural': 'Gider Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-period', 'created_at'], 'verbose_name': 'Gelir Kaydı', 'verbose_name_plural': 'Gelir Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='reciever',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alıcı / Firma / Kişi'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Banka Transferi / EFT / Havale'), ('cash', 'Nakit'), ('credit_card', 'Kredi Kartı'), ('other', 'Diğer')], default='bank', max_length=20, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.CreateModel(
            name='RegularExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (TL)')),
                ('reciever', models.CharField(max_length=200, verbose_name='Alıcı / Firma / Kişi')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi (Opsiyonel)')),
                ('frequency', models.CharField(choices=[('monthly', 'Aylık'), ('quarterly', '3 Aylık'), ('yearly', 'Yıllık')], default='monthly', max_length=20, verbose_name='Frekans')),
                ('paymentDay', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Örn: 15, 30. Boş bırakılırsa ödeme günü belirtilmemiş olur.', null=True, verbose_name='Ödeme Günü')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Açıklama / Detay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regular_expenses', to='finance.expensecategory', verbose_name='Kategori')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Oluşturan')),
            ],
            options={
                'verbose_name': 'Düzenli Gider',
                'verbose_name_plural': 'Düzenli Giderler',
                'ordering': ['-start_date'],
            },
        ),
    ]
