# Generated by Django 6.1.1 on 2026-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Gider Kaydı', 'verbose_name_plural': 'Gider Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
