# Generated by Django 6.1.1 on 2026-09-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expense_options_expense_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='regular_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='finance.regularexpense', verbose_name='Düzenli gider kaynağı'),
        ),
    ]
