# Generated by Django 6.1 on 2026-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_expense_regular_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("fee", "Aidat"),
                    ("donation", "Bağış"),
                    ("membership", "Üyelik"),
                    ("bank_transfer", "Banka / Havale Geliri"),
                    ("sponsorship", "Sponsorluk"),
                    ("camping_fee", "Kamp Ücreti"),
                    ("other", "Diğer"),
                ],
                default="fee",
                max_length=30,
                verbose_name="Ödeme Türü",
            ),
        ),
    ]
