# Generated by Django 6.1 on 2026-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_remove_athlete_fee_history"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paymentrecord",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("fee", "Aidat"),
                    ("donation", "Bağış"),
                    ("membership", "Üyelik"),
                    ("bank_transfer", "Banka / Havale Geliri"),
                    ("equipment_sale", "Malzeme Satışı"),
                    ("sponsorship", "Sponsorluk"),
                    ("camping_fee", "Kamp Ücreti"),
                    ("other", "Diğer"),
                ],
                default="fee",
                max_length=30,
                verbose_name="Ödeme Türü",
            ),
        ),
    ]
