# Generated by Django 6.1.1 on 2026-09-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_paymentrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Malzeme Türü')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'ordering': ['name'],
            },
        ),
    ]
