# Generated by Django 6.1.1 on 2026-09-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Birim Fiyatı')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='finance.equipment', verbose_name='Malzeme')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_sale_items', to='finance.paymentrecord', verbose_name='Satış')),
            ],
            options={
                'verbose_name': 'Malzeme Satış Satırı',
                'verbose_name_plural': 'Malzeme Satış Satırları',
            },
        ),
    ]
