# Generated by Django 6.1 on 2026-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_backfill_equipment_sale_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.IntegerField(verbose_name="Fiyat"),
        ),
        migrations.AlterField(
            model_name="equipmentsaleitem",
            name="unit_price",
            field=models.IntegerField(verbose_name="Satış Birim Fiyatı"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.IntegerField(verbose_name="Tutar (TL)"),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="amount",
            field=models.IntegerField(verbose_name="Tutar (TL)"),
        ),
        migrations.AlterField(
            model_name="regularexpense",
            name="amount",
            field=models.IntegerField(verbose_name="Tutar (TL)"),
        ),
        migrations.AlterField(
            model_name="teamfeehistory",
            name="monthly_fee",
            field=models.IntegerField(),
        ),
    ]
