# Generated by Django 6.1 on 2026-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_alter_equipment_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Bekliyor"),
                    ("paid", "Ödendi"),
                    ("cancelled", "İptal Edildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Gider Durumu",
            ),
        ),
    ]
