# Generated by Django 6.1.1 on 2026-09-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_equipmentstockmovement_sale_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.expensecategory', verbose_name='Üst Kategori'),
        ),
    ]
