# Generated by Django 6.1 on 2026-09-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0019_expensecategory_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="equipment_images/", verbose_name="Görsel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="finance.equipment",
                        verbose_name="Malzeme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Malzeme görseli",
                "verbose_name_plural": "Malzeme görselleri",
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
