# Generated by Django 6.1 on 2026-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_equipmentimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="color",
            field=models.CharField(
                blank=True, default="Standart", max_length=50, verbose_name="Renk"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="size",
            field=models.CharField(
                blank=True, default="Standart", max_length=20, verbose_name="Beden"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Malzeme Türü"),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("name", "color", "size"), name="unique_equipment_variant"
            ),
        ),
    ]
