# Generated by Django 6.1 on 2026-09-16 13:33

from django.db import migrations, models


def move_flat_variants_to_json(apps, schema_editor):
    Equipment = apps.get_model('finance', 'Equipment')
    for equipment in Equipment.objects.all():
        color = (equipment.color or 'Standart').strip()
        size = (equipment.size or 'Standart').strip()
        equipment.variants = [{'color': color, 'sizes': [size]}]
        equipment.save(update_fields=['variants'])


def restore_flat_variants(apps, schema_editor):
    Equipment = apps.get_model('finance', 'Equipment')
    for equipment in Equipment.objects.all():
        variant = (equipment.variants or [{}])[0]
        equipment.color = variant.get('color', 'Standart')
        equipment.size = (variant.get('sizes') or ['Standart'])[0]
        equipment.save(update_fields=['color', 'size'])


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0021_equipment_color_equipment_size_alter_equipment_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipment",
            name="unique_equipment_variant",
        ),
        migrations.AddField(
            model_name="equipment",
            name="variants",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Renk ve beden seçenekleri"
            ),
        ),
        migrations.RunPython(move_flat_variants_to_json, restore_flat_variants),
        migrations.RemoveField(
            model_name="equipment",
            name="color",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="size",
        ),
    ]
