# Generated by Django 6.1 on 2026-09-16 13:40

from django.db import migrations, models


def split_variants(apps, schema_editor):
    Equipment = apps.get_model('finance', 'Equipment')
    for equipment in Equipment.objects.all():
        colors = []
        sizes = []
        for variant in equipment.variants or []:
            color = str(variant.get('color', '')).strip()
            if color and color not in colors:
                colors.append(color)
            for size in variant.get('sizes', []) or []:
                size = str(size).strip()
                if size and size not in sizes:
                    sizes.append(size)
        equipment.colors = colors
        equipment.sizes = sizes
        equipment.save(update_fields=['colors', 'sizes'])


def combine_variants(apps, schema_editor):
    Equipment = apps.get_model('finance', 'Equipment')
    for equipment in Equipment.objects.all():
        colors = equipment.colors or ['']
        sizes = equipment.sizes or ['']
        equipment.variants = [
            {'color': color, 'sizes': sizes}
            for color in colors
        ]
        equipment.save(update_fields=['variants'])


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0022_remove_equipment_unique_equipment_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="colors",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Renk seçenekleri"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="sizes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Beden seçenekleri"
            ),
        ),
        migrations.RunPython(split_variants, combine_variants),
        migrations.RemoveField(
            model_name="equipment",
            name="variants",
        ),
    ]
