# Generated by Django 6.1 on 2026-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0023_remove_equipment_variants_equipment_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentsaleitem",
            name="selected_color",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Seçilen renk"
            ),
        ),
        migrations.AddField(
            model_name="equipmentsaleitem",
            name="selected_size",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Seçilen beden"
            ),
        ),
    ]
