# Generated by Django 6.1 on 2026-09-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0024_equipmentsaleitem_selected_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentstockmovement",
            name="selected_color",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Renk"
            ),
        ),
        migrations.AddField(
            model_name="equipmentstockmovement",
            name="selected_size",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Beden"
            ),
        ),
    ]
