# Generated by Django 6.1 on 2026-08-27 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=50, verbose_name="Soyad")),
                (
                    "tc_identity",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="T.C. Kimlik No",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Doğum Tarihi")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Erkek"), ("F", "Kadın")],
                        max_length=1,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Okul"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Lisans No"
                    ),
                ),
                ("joined_date", models.DateField(verbose_name="Kulübe Katılım Tarihi")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="athlete_photos/",
                        verbose_name="Fotoğraf",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif Sporcu mu?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Veli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sporcu",
                "verbose_name_plural": "Sporcular",
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
