# Generated by Django 6.1 on 2026-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Onay Bekliyor"),
                    ("approved", "Onaylandı"),
                    ("rejected", "Reddedildi"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Onay Durumu",
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Aktif Sporcu mu?"),
        ),
    ]
