# Generated by Django 6.1 on 2026-08-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0002_athlete_status_alter_athlete_is_active"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="custom_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Boş bırakılırsa takımın varsayılan aidatı uygulanır. Burslu için 0 girebilirsiniz.",
                max_digits=10,
                null=True,
                verbose_name="Özel Aidat Tutar (TL)",
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athletes",
                to="teams.team",
                verbose_name="Bağlı Olduğu Takım",
            ),
        ),
    ]
