# Generated by Django 6.1.1 on 2026-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_custom_fee_athlete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boş bırakılırsa indirim uygulanmaz.', max_digits=5, null=True, verbose_name='İndirim Yüzdesi'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='regular_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Düzenli Ödeme Tarihi'),
        ),
    ]
