# Generated by Django 6.1.1 on 2026-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='regular_payment_date',
        ),
        migrations.AddField(
            model_name='athlete',
            name='regular_payment_day',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Düzenli Ödeme Günü'),
        ),
    ]
