# Generated by Django 6.1 on 2026-09-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0006_remove_athlete_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="custom_fee",
            field=models.IntegerField(
                blank=True,
                help_text="Boş bırakılırsa takımın varsayılan aidatı uygulanır. Burslu için 0 girebilirsiniz.",
                null=True,
                verbose_name="Özel Aidat Tutar (TL)",
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="discount_percentage",
            field=models.IntegerField(
                blank=True,
                help_text="Boş bırakılırsa indirim uygulanmaz.",
                null=True,
                verbose_name="İndirim Yüzdesi",
            ),
        ),
    ]
