# Generated by Django 6.1 on 2026-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0009_alter_athlete_private_lesson_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="last_sms_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Son SMS Gönderim Zamanı"
            ),
        ),
    ]
