# Generated by Django 6.1.1 on 2026-10-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_parents(apps, schema_editor):
    Athlete = apps.get_model('athletes', 'Athlete')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    parents = {}
    for user in User.objects.filter(role='parent').exclude(email=''):
        parents.setdefault(user.email.strip().lower(), user)
    for athlete in Athlete.objects.filter(user__isnull=True).exclude(parent_email=''):
        user = parents.get(athlete.parent_email.strip().lower())
        if user:
            Athlete.objects.filter(pk=athlete.pk).update(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0011_athlete_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "parent"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Veli hesabı",
            ),
        ),
        migrations.RunPython(link_parents, migrations.RunPython.noop),
    ]
